[package]
name = "gitui"
version = "0.12.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
description = "blazing fast terminal-ui for git"
edition = "2018"
exclude = [".github/*", ".vscode/*"]
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["git", "gui", "cli", "terminal", "ui"]

[dependencies]
scopetime = { path = "./scopetime", version = "0.1" }
asyncgit = { path = "./asyncgit", version = "0.11" }
crossterm = { version = "0.18", features = ["serde"] }
clap = { version = "2.33", default-features = false }
tui = { version = "0.13", default-features = false, features = ['crossterm', 'serde'] }
bytesize = { version = "1.0.1", default-features = false }
itertools = "0.9"
rayon-core = "1.9"
log = "0.4"
simplelog = { version = "0.8", default-features = false }
dirs-next = "2.0"
crossbeam-channel = "0.5"
scopeguard = "1.1"
bitflags = "1.2"
chrono = "0.4"
backtrace = "0.3"
ron = "0.6"
serde = "1.0"
anyhow = "1.0.36"
unicode-width = "0.1"
textwrap = "0.13"

[target.'cfg(all(target_family="unix",not(target_os="macos")))'.dependencies]
which = "4.0"

# pprof is not available on windows
[target.'cfg(not(windows))'.dependencies]
pprof = { version = "0.3", features = ["flamegraph"], optional = true }

[badges]
maintenance = { status = "passively-maintained" }

[features]
default = ["macos-user-home-config"]
timing = ["scopetime/enabled"]
# If enabled, use `$XDG_CONFIG_HOME/gitui/key_config.ron" for config path on
# macOS, like on Unix, instead of using `$HOME/Library/Application Support/`.
macos-user-home-config = []

[workspace]
members = ["asyncgit", "scopetime"]

[profile.release]
lto = true
# Optimize for speed; we don't need to distribute binary locally so this is
# fine!
opt-level = 3
codegen-units = 1

# make debug build as fast as release 
# usage of utf8 encoding inside tui 
# makes their debug profile slow
[profile.dev.package."tui"]
opt-level = 3
